= devops-stack-module-cluster-kind

A https://devops-stack.io[DevOps Stack] module to deploy a KinD cluster based on Docker.

This cluster module is mainly used to deploy a *single-node* Kubernetes cluster used for testing and development as well as for onboarding new users of the DevOps Stack.

Because KinD is nothing more than a Kubernetes cluster running inside a container, it is required that you have Docker up and running on your machine (the documentation to install Docker is available here https://docs.docker.com/engine/install/[here]).

== Usage

This module can be declared by adding the following block on your Terraform configuration:

[source,terraform]
----
module "kind" {
  source = "git::https://github.com/camptocamp/devops-stack-module-kind.git?ref=<RELEASE>"

  cluster_name = local.cluster_name
}
----

You can configure the version of Kubernetes by passing the variable `kubernetes_version`. This variable is nothing more than the tag of the image that is to be deployed. You can see the usable versions in https://hub.docker.com/r/kindest/node/tags[Docker Hub]. 

[source,terraform]
----
module "kind" {
  source = "git::https://github.com/camptocamp/devops-stack-module-kind.git?ref=<RELEASE>"

  cluster_name = local.cluster_name

  kubernetes_version = "1.25.3"
}
----

It is also possible to configure the ports that are mapped between the KinD container and your machine. This is needed in order to access services that you deploy inside the cluster. By default, this module already maps the ports needed for HTTP and HTTPS traffic.

[source,terraform]
----
module "kind" {
  source = "git::https://github.com/camptocamp/devops-stack-module-kind.git?ref=<RELEASE>"

  cluster_name = local.cluster_name

  extra_port_mappings = ["tcp/22", "udp/53"]
}
----

// This link does not have a working example before we have merged the v1 branch to master.
TIP: A test deployment of the DevOps Stack is available https://github.com/camptocamp/devops-stack/tree/master/tests/kind-kind[here].

== Technical Reference

=== Dependencies

Obviously, since this module deploys the cluster, it does not depend on any other module of the DevOps Stack. The only thing you'll probably want to configure are some `locals` with some common variables used on all the modules:

[source,terraform]
----
locals {
  cluster_name     = "gh-v1-cluster"
  cluster_issuer   = "ca-issuer"
  argocd_namespace = "argocd"
}
----

// BEGIN_TF_DOCS
=== Requirements

The following requirements are needed by this module:

- [[requirement_docker]] <<requirement_docker,docker>> (~> 2.23.1)

- [[requirement_kind]] <<requirement_kind,kind>> (~> 0.0.16)

=== Providers

The following providers are used by this module:

- [[provider_docker]] <<provider_docker,docker>> (~> 2.23.1)

- [[provider_kind]] <<provider_kind,kind>> (~> 0.0.16)

=== Modules

No modules.

=== Resources

The following resources are used by this module:

- https://registry.terraform.io/providers/tehcyx/kind/latest/docs/resources/cluster[kind_cluster.cluster] (resource)
- https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/data-sources/network[docker_network.kind] (data source)

=== Required Inputs

No required inputs.
=== Optional Inputs

The following input variables are optional (have default values):

==== [[input_cluster_name]] <<input_cluster_name,cluster_name>>

Description: n/a

Type: `string`

Default: `"kind"`

==== [[input_kubernetes_version]] <<input_kubernetes_version,kubernetes_version>>

Description: n/a

Type: `string`

Default: `"v1.25.3"`

=== Outputs

The following outputs are exported:

==== [[output_kind_subnet]] <<output_kind_subnet,kind_subnet>>

Description: Kind IPv4 docker network subnet.

==== [[output_parsed_kubeconfig]] <<output_parsed_kubeconfig,parsed_kubeconfig>>

Description: Kubeconfig blocks to configure Terraform providers.

==== [[output_raw_kubeconfig]] <<output_raw_kubeconfig,raw_kubeconfig>>

Description: Raw kubeconfig file for kubectl access.
// END_TF_DOCS

=== Reference in table format 

.Show tables
[%collapsible]
====
// BEGIN_TF_TABLES
= Requirements

[cols="a,a",options="header,autowidth"]
|===
|Name |Version
|[[requirement_docker]] <<requirement_docker,docker>> |~> 2.23.1
|[[requirement_kind]] <<requirement_kind,kind>> |~> 0.0.16
|===

= Providers

[cols="a,a",options="header,autowidth"]
|===
|Name |Version
|[[provider_docker]] <<provider_docker,docker>> |~> 2.23.1
|[[provider_kind]] <<provider_kind,kind>> |~> 0.0.16
|===

= Resources

[cols="a,a",options="header,autowidth"]
|===
|Name |Type
|https://registry.terraform.io/providers/tehcyx/kind/latest/docs/resources/cluster[kind_cluster.cluster] |resource
|https://registry.terraform.io/providers/kreuzwerker/docker/latest/docs/data-sources/network[docker_network.kind] |data source
|===

= Inputs

[cols="a,a,a,a,a",options="header,autowidth"]
|===
|Name |Description |Type |Default |Required
|[[input_cluster_name]] <<input_cluster_name,cluster_name>>
|n/a
|`string`
|`"kind"`
|no

|[[input_kubernetes_version]] <<input_kubernetes_version,kubernetes_version>>
|n/a
|`string`
|`"v1.25.3"`
|no

|===

= Outputs

[cols="a,a",options="header,autowidth"]
|===
|Name |Description
|[[output_kind_subnet]] <<output_kind_subnet,kind_subnet>> |Kind IPv4 docker network subnet.
|[[output_parsed_kubeconfig]] <<output_parsed_kubeconfig,parsed_kubeconfig>> |Kubeconfig blocks to configure Terraform providers.
|[[output_raw_kubeconfig]] <<output_raw_kubeconfig,raw_kubeconfig>> |Raw kubeconfig file for kubectl access.
|===
// END_TF_TABLES
====
